# Generated by Django 2.0.2 on 2018-03-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=50)),
                ('g_permission', models.CharField(choices=[('ADD', 'ADDNEW'), ('EDIT', 'EDIT'), ('DEL', 'DELETE')], max_length=4)),
                ('g_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_name', models.CharField(max_length=100)),
                ('r_desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=201)),
                ('password', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('hobbies', models.TextField()),
                ('u_desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='role',
            name='r_user',
            field=models.ManyToManyField(to='user.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='g_user',
            field=models.ManyToManyField(to='user.User'),
        ),
    ]
