# Generated by Django 2.0.2 on 2018-03-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='g_user',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='role',
            old_name='r_user',
            new_name='user',
        ),
    ]
